#!/bin/bash -e
# regenerate phpmyadmin pmadb password

. /etc/default/inithooks

PASSWORD=$(mcookie)
CONF=/etc/phpmyadmin/config-db.php

sed -i "/^\$dbpass/ c \$dbpass='$PASSWORD';" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=phpmyadmin --pass="$PASSWORD"
