<?php

/**
 * @file
 * Module file for l10n_suggestions.
 */

require_once(dirname(__FILE__) . '/includes/common.inc');

/**
 * Implements hook_help().
 */
                               /*
function l10n_suggestions_help($path, $args) {
  switch($path)
    {
      case 'translations/get':
        $help = t('Get translation suggestions for a given string.');
        break;

      case 'translations/vote':
        $help = t('Vote the best translation for a string, or suggest a better translation.');
        break;
    }

  return $help;
}
                               */

/**
 * Implements hook_menu().
 */
function l10n_suggestions_menu() {

  $items['translation'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title'           => 'Translations',
    'description'     => 'Vote the best translation for a string, or suggest a better translation.',
    'page callback'   => 'l10n_suggestions_vote',
    'file'            => 'includes/translations/vote.inc',
    'access callback' => TRUE,
  );

  $items['translations/default'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title'           => 'Vote',
    //'description'     => 'Vote the best translation for a string, or suggest a better translation.',
    //'page callback'   => 'l10n_suggestions_vote',
    //'file'            => 'includes/translations/vote.inc',
    //'access callback' => TRUE,
    'weight'          => 1,
  );

  $items['translations/search'] = array(
    'type' => MENU_LOCAL_TASK,
    'title'           => 'Search',
    'description'     => 'Search strings and translations using various filters.',
    'page callback'   => 'l10n_suggestions_search',
    'file'            => 'includes/translations/search.inc',
    'access callback' => TRUE,
    'weight'          => 2,
  );

  $items['translations/get'] = array(
    'type'            => MENU_CALLBACK,
    'title'           => 'Get l10n Translation',
    'description'     => 'Get translation suggestions for a given string.',
    'page callback'   => 'l10n_suggestions_get',
    'file'            => 'includes/translations/get.inc',
    'access callback' => TRUE,
  );

  // Autocomplete callback for project textfields.
  $items['translations/autocomplete/project'] = array(
    'type'            => MENU_CALLBACK,
    'title'           => 'Project autocomplete',
    'page callback'   => 'l10n_suggestions_project_autocomplete',
    'file'            => 'includes/ajax_callbacks.inc',
    //'access arguments' => array('access localization community'),
    'access callback' => TRUE,
  );

  // Autocomplete callback for user textfields.
  $items['translations/autocomplete/user'] = array(
    'type'            => MENU_CALLBACK,
    'title'           => 'User autocomplete',
    'page callback'   => 'l10n_suggestions_user_autocomplete',
    'file'            => 'includes/ajax_callbacks.inc',
    //'access arguments' => array('access localization community'),
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function l10n_suggestions_theme($existing, $type, $theme, $path) {
  return array(
    'l10n_suggestions_filter_form_element' => array(
      'render element' => 'element',
    ),
    'l10n_suggestions_translate_translation' => array(
      'render element' => 'element',
    ),
    'l10n_suggestions_translate_actions' => array(
      'render element' => 'element',
    ),
    'l10n_suggestions_in_context' => array(
      'variables' => array('source' => NULL),
    ),
    'l10n_suggestions_translate_radio' => array(
      'render element' => 'element',
    ),
    'l10n_suggestions_translate_source' => array(
      'render element' => 'element',
    ),
    'l10n_suggestions_translate_translation_list' => array(
      'render element' => 'element',
    ),
    'l10n_suggestions_translate_table' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_init().
 *
 * Add stylesheets and block search engines from web application pages.
 */
function l10n_suggestions_init() {
  if (arg(0) == 'translation') {
    drupal_add_css(drupal_get_path('module', 'l10n_suggestions') . '/l10n_suggestions.css');
    // For the translation overview pages. This is used to present admin page like panels.
    drupal_add_css(drupal_get_path('module', 'system') . '/admin.css');
  }

  // Check if language is RTL
  $languages = l10n_suggestions_get_languages();
  $lng = arg(2);
  if (array_key_exists($lng, $languages)) {
    // Add RTL style if the current language's direction is RTL
    if ($languages[$lng]['direction'] == LANGUAGE_RTL) {
      drupal_add_css(drupal_get_path('module', 'l10n_suggestions') . '/l10n_suggestions-rtl.css');
    }
  }

  //variable_set('l10n_suggestions_voting_mode', 'multiple');  //debug
  variable_set('l10n_suggestions_voting_mode', 'single');  //debug
}

?>