
This is a Drupal installation profile for B-Translator Server.

* Installation

  Installation is done inside a Docker container.

  + Modify and customize the settings:
    #+BEGIN_EXAMPLE
    cp btr_server/install/settings.sh cfg.sh
    vim cfg.sh
    #+END_EXAMPLE

  + Build a Docker image:
    #+BEGIN_EXAMPLE
    btr_server/docker-build.sh cfg.sh --git_branch=master
    less -r nohup-btr_server-master.out
    #+END_EXAMPLE
    This will create a docker image, named =btr_server:master= with a
    minimal ubuntu system and everything that is needed for the normal
    work of the system.

  + Create a Docker container like this:
    #+BEGIN_EXAMPLE
    docker images
    docker run -d --name=btr_server --hostname=example.org \
	       -p 80:80 -p 443:443 btr_server:master
    #+END_EXAMPLE
    Then you can stop and start the container with =docker stop btr_server=
    and =docker start btr_server=.

  If it is installed on a local machine (for testing or development),
  add the domain name =example.org= on ~/etc/hosts~:
  #+BEGIN_EXAMPLE
  127.0.0.1 example.org
  #+END_EXAMPLE
  This way it can be accessed by typing =https://example.org=
  on the browser location (not =https://127.0.0.1= or
  =https://localhost=).


* What is B-Translator

  The codename *B-Translator* can be decoded like *Bee Translator*,
  since it aims at collecting very small translation contributions
  from a wide crowd of people and to dilute them into something
  useful.

  It can also be decoded like *Be Translator*, as an invitation to
  anybody to give his small contribution for translating programs or
  making their translations better.


* Contacts

  - Email: info@btranslator.org

  - Follow on Twitter: https://twitter.com/b_translator

  - Discussion group/forum
    + Email: /btranslator@googlegroups.com/
    + Web: https://groups.google.com/forum/?fromgroups&hl=en#!forum/btranslator
    + Google+ Community: https://plus.google.com/u/0/communities/109327047119841706609

  - Chat/IRC: *#btranslator* on *irc.freenode.net*

  - Misc
    + Homepage: http://info.btranslator.org
    + Wiki: https://github.com/B-Translator/btr_server/wiki
    + Issues: https://github.com/B-Translator/btr_server/issues


* Sites

  Sites using B-Translator:
  - https://l10n.org.al - Albanian translations.

  To install and setup your site you would need some basic skills on
  Ubuntu server administration and Drupal administration.
