
This is a Drupal installation profile for B-Translator Server.

* Installation

  The recommended way of installation for a production server is to
  install it inside a chroot, in /trusty/ (ubuntu 14.04). Assuming
  that we have already installed a minimal ubuntu server 14.04
  (trusty), btr_server can be installed in it like this:
  #+BEGIN_EXAMPLE
  mkdir /var/chroot
  cd /var/chroot/
  git clone https://github.com/B-Translator/btr_client.git
  git clone https://github.com/B-Translator/btr_server.git
  cp btr_server/install/settings.sh btr_server/config.sh
  vim btr_server/config.sh
  nohup time nice btr_server/{install/chroot.sh,config.sh} &
  tail -f nohup.out
  less -r nohup.out
  #+END_EXAMPLE

  This will install in ~/var/chroot/~ a minimal ubuntu system,
  B-Translator Server, B-Translator Client, and everything that is
  needed for the normal work of the system. It will also make the
  neccessary common configurations of the system.

  The installation script will create as well the init script
  ~/etc/init.d/chroot-btr~, which can be used to start and stop the
  services inside the chroot:
  #+BEGIN_EXAMPLE
  /etc/init.d/chroot-btr start
  /etc/init.d/chroot-btr stop
  #+END_EXAMPLE

* Installation in a docker container

  This is almost the same as the installation above, except that
  instead of ~install/chroot.sh~ you call ~install/docker.sh~:
  #+BEGIN_EXAMPLE
  nohup time nice btr_server/{install/docker.sh,config.sh} &
  #+END_EXAMPLE

  Then to start and stop B-Translator you do:
  #+BEGIN_EXAMPLE
  docker.io start btr
  docker.io stop btr
  #+END_EXAMPLE


* What is B-Translator

  The codename *B-Translator* can be decoded like *Bee Translator*,
  since it aims at collecting very small translation contributions
  from a wide crowd of people and to dilute them into something
  useful.

  It can also be decoded like *Be Translator*, as an invitation to
  anybody to give his small contribution for translating programs or
  making their translations better.


* Contacts

  - Email: info@btranslator.org

  - Follow on Twitter: https://twitter.com/b_translator

  - Discussion group/forum
    + Email: /btranslator@googlegroups.com/
    + Web: https://groups.google.com/forum/?fromgroups&hl=en#!forum/btranslator
    + Google+ Community: https://plus.google.com/u/0/communities/109327047119841706609

  - Chat/IRC: *#btranslator* on *irc.freenode.net*

  - Misc
    + Homepage: http://info.btranslator.org
    + Wiki: https://github.com/B-Translator/btr_server/wiki
    + Issues: https://github.com/B-Translator/btr_server/issues


* Sites

  Sites using B-Translator:
  - https://l10n.org.al - Albanian translations.

  To install and setup your site you would need some basic skills on
  Ubuntu server administration and Drupal administration.
