
This is a Drupal installation profile for B-Translator.

* Installation

  The recommended way of installation for a production server is to
  install it inside a chroot, in precise (ubuntu 12.04). Assuming that
  we have already installed a minimal ubuntu server 12.04 (precise),
  btranslator can be installed in it like this:
  #+BEGIN_EXAMPLE
  sudo mkdir /var/chroot
  cd /var/chroot/
  sudo git clone https://github.com/dashohoxha/B-Translator.git
  sudo B-Translator/install/install.sh btr
  #+END_EXAMPLE

  This will install in ~/var/chroot/btr~ a minimal ubuntu system,
  B-Translator, and everything that is needed for the normal work of
  the system. It will also make the neccessary common configurations
  of the system and prompt for customizing it (for example the domain,
  email address, etc.)
  
  The installation script will also create the init script
  ~/etc/init.d/chroot-btr~, which can be used to start and stop the services
  inside the chroot:
  #+BEGIN_EXAMPLE
  service chroot-btr start
  service chroot-btr stop
  #+END_EXAMPLE

  *Note:* The default options of the script are: =--arch=i386=,
   =--suite=precise= and =--mirror=http://archive.ubuntu.com/ubuntu=
   . If you want to use something different, you have to give the
   option explicitly on the command line.

  For development purposes, probably it is better to install B-Translator
  like this (inside a chroot):
  #+BEGIN_EXAMPLE
  cd /var/www/
  sudo git clone https://github.com/dashohoxha/B-Translator.git
  sudo B-Translator/install/dev/all.sh
  #+END_EXAMPLE

  For more detailed information about installation see *docs/INSTALL.org*.

* What means B-Translator

  The codename *B-Translator* can be decoded like *Bee Translator*,
  since it aims at collecting very small translation contributions
  from a wide crowd of people and to dilute them into something
  useful.

  It can also be decoded like *Be Translator*, as an invitation to
  anybody to give his small contribution for translating programs or
  making their translations better.

  If you could come up with some other interesting explanations,
  please let me know.

* The goals of the project

  This software helps to get feedback about l10n (translations of the
  programs). It also helps to unify all the different translations and
  to ensure consistency among the translations.

  The motivation for developing such a software is that the
  traditional (current) l10n workflow requires highly dedicated
  people, and does not allow (or at least does not facilitate) small
  contributions from random people that do not have such a high
  dedication, determination and enough free time.

  Also, the process of reviewing and correcting translations is not
  easy and does not facilitate the feedback from the users of the
  translated programs. Although the translators are usually very good
  and professional, they can make mistakes too, and sometimes they may
  miss the best translation for some certain terms. Some feedback from
  the crowd of the users would be more than welcome, if there are
  tools to collect and facilitate it.

  Another problem with translations is that sometimes they are not
  consistent. The same string has different translations in different
  programs, and sometimes even the same translator may have provided
  different translations for the same string in different cases.

  To summarize, the problems that this software tries to solve are
  these:
  + Merging translations from different sources (for example
    translations made on Launchpad and those made on KDE or GNOME).
  + Helping to ensure consistency among the translations.
  + Getting feedback about the translations from a wide crowd of
    people and users. This feedback can be in terms of votes for the
    best translation (when there are more than one translations for
    the same string), or it can be a new alternative translation (for
    an existing translation), or it can be a new translation
    suggestion (for a string that is not translated yet).


* Contacts

  - Discussion group/forum
    + Email: /btranslator@googlegroups.com/
    + Web: https://groups.google.com/forum/?fromgroups&hl=en#!forum/btranslator

  - Chat/IRC: *#btranslator* on *irc.freenode.net* 

  - Misc
    + Issues: https://github.com/dashohoxha/B-Translator/issues
    + Wiki: https://github.com/dashohoxha/B-Translator/wiki
    + Homepage: http://dashohoxha.github.com/B-Translator/


* Demo

  - https://l10n.org.al/translations -- It is actually a production site for
    translations into Albanian.

  Would you like to setup a demo installation for your language? Contact me
  to discuss about the requirements (you need to find at least one Drupal
  developer to manage/maintain your site).


* Documentation

  - Project docs: https://github.com/dashohoxha/B-Translator/tree/master/docs
  - Code docs generated by doxygen:
    + html: https://btranslator.org/downloads/btranslator-doxygen/
    + html.tgz: https://btranslator.org/downloads/btranslator-doxygen.tgz
    + pdf: https://btranslator.org/downloads/btranslator-doxygen.tgz
