
This is a Drupal installation profile for B-Translator Server.

* Installation

  Installation is done inside a Docker container. For instructions
  about installing Docker see: https://docs.docker.com/installation/

  + Create a working directory:
    #+BEGIN_EXAMPLE
    mkdir workdir/
    #+END_EXAMPLE

  + Link the docker directory inside the working directory:
    #+BEGIN_EXAMPLE
    cd workdir/
    ln -s ../btr_server/docker .
    #+END_EXAMPLE

  + Modify and customize the settings:
    #+BEGIN_EXAMPLE
    cp docker/settings.sh .
    vim settings.sh
    #+END_EXAMPLE

  + Build a Docker image:
    #+BEGIN_EXAMPLE
    docker/build.sh settings.sh
    tail -f logs/nohup-btr_server-master-20150929.out
    less -r logs/nohup-btr_server-master-20150929.out
    #+END_EXAMPLE
    This will create a docker image, named =btr_server:master= with a
    minimal ubuntu system and everything that is needed for the normal
    work of the Drupal application.

  + Create a Docker container like this:
    #+BEGIN_EXAMPLE
    docker/create.sh
    #+END_EXAMPLE
    It will create a container with port forwarding like this: =-p
    80:80 -p 443:443 -p 2201:2201=. If you don't like the default port
    forwarding, edit ~config~ and modify it.

  + Now you can start and stop the container with =docker/start.sh=
    and =docker/stop.sh=, enter the shell of the container with
    =docker/enter.sh=, etc.

  + If =development=true= is set on the settings, then the code of the
    application inside the container will be linked to the directories
    ~btr_server/~ and ~btr_client/~ inside the workdir, so that you
    can edit and work on it easily.

  + If it is installed on a local machine (for testing or
    development), add the domain names =btr.example.org= and
    =l10n.example.org= on ~/etc/hosts~, like this:
    #+BEGIN_EXAMPLE
    127.0.0.1 btr.example.org
    127.0.0.1 l10n.example.org
    #+END_EXAMPLE
    This way it can be accessed by typing =https://btr.example.org=
    and =https://l10n.example.org= on the browser location.

  + To change the configuration, either run =docker/reconfig.sh= and
    give the new settings interactively, or edit
    ~btr_server/options.sh~ and then run =docker/reconfig.sh options.sh=.

* What is B-Translator

  The codename *B-Translator* can be decoded like *Bee Translator*,
  since it aims at collecting very small translation contributions
  from a wide crowd of people and to dilute them into something
  useful.

  It can also be decoded like *Be Translator*, as an invitation to
  anybody to give his small contribution for translating programs or
  making their translations better.


* Contacts

  - Email: info@btranslator.org

  - Follow on Twitter: https://twitter.com/b_translator

  - Discussion group/forum
    + Email: /btranslator@googlegroups.com/
    + Web: https://groups.google.com/forum/?fromgroups&hl=en#!forum/btranslator
    + Google+ Community: https://plus.google.com/u/0/communities/109327047119841706609

  - Chat/IRC: *#btranslator* on *irc.freenode.net*

  - Misc
    + Homepage: http://info.btranslator.org
    + Wiki: https://github.com/B-Translator/btr_server/wiki
    + Issues: https://github.com/B-Translator/btr_server/issues


* Sites

  Sites using B-Translator:
  - https://l10n.org.al - Albanian translations.

  To install and setup your site you would need some basic skills on
  Ubuntu server administration and Drupal administration.
