
This is a Drupal installation profile for B-Translator.

* Installation
  A full distro including Drupal core (with patches) and the
  /btranslation/ installation profile can be built like this:
  #+BEGIN_EXAMPLE
  cd /var/www/
  sudo wget https://raw.github.com/dashohoxha/B-Translator/master/install.sh
  sudo ./install.sh [directory]
  #+END_EXAMPLE

* Requirements

  + LAMP:
    #+BEGIN_EXAMPLE
    sudo apt-get install apache2 php5 mysql-server phpmyadmin php5-curl php-apc
    #+END_EXAMPLE

  + drush make:
    #+BEGIN_EXAMPLE
    sudo apt-get install drush
    mkdir ~/.drush
    cd ~/.drush
    wget http://ftp.drupal.org/files/projects/drush_make-6.x-2.3.tar.gz
    tar xfz drush_make-6.x-2.3.tar.gz
    #+END_EXAMPLE

  + Other tools:
    #+BEGIN_EXAMPLE
    sudo apt-get install git gawk mercurial translate-toolkit
    #+END_EXAMPLE


* What means B-Translator

  The codename *B-Translator* can be decoded like *Bee Translator*,
  since it aims at collecting very small translation contributions
  from a wide crowd of people and to dilute them into something
  useful.

  It can also be decoded like *Be Translator*, as an invitation to
  anybody to give his small contribution for translating programs or
  making their translations better.

  If you could come up with some other interesting explanations,
  please let me know.

* The goals of the project

  This software helps to get feedback about l10n (translations of the
  programs). It also helps to unify all the different translations and
  to ensure consistency among the translations.

  The motivation for developing such a software is that the
  traditional (current) l10n workflow requires highly dedicated
  people, and does not allow (or at least does not facilitate) small
  contributions from random people that do not have such a high
  dedication, determination and enough free time.

  Also, the process of reviewing and correcting translations is not
  easy and does not facilitate the feedback from the users of the
  translated programs. Although the translators are usually very good
  and professional, they can make mistakes too, and sometimes they may
  miss the best translation for some certain terms. Some feedback from
  the crowd of the users would be more than welcome, if there are
  tools to collect and facilitate it.

  Another problem with translations is that sometimes they are not
  consistent. The same string has different translations in different
  programs, and sometimes even the same translator may have provided
  different translations for the same string in different cases.

  To summarize, the problems that this software tries to solve are
  these:
  + Merging translations from different sources (for example
    translations made on Launchpad and those made on KDE or GNOME).
  + Helping to ensure consistency among the translations.
  + Getting feedback about the translations from a wide crowd of
    people and users. This feedback can be in terms of votes for the
    best translation (when there are more than one translations for
    the same string), or it can be a new alternative translation (for
    an existing translation), or it can be a new translation
    suggestion (for a string that is not translated yet).
    


