#+TITLE:     Project Management, Tasks and Notes
#+AUTHOR:    Dashamir Hoxha
#+EMAIL:     dashohoxha@gmail.com
##+DATE:      2012-01-04 Wed
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:overview toc:t ltoc:t mouse:#aadddd buttons:0 path:org-info.js
##+EXPORT_SELECT_TAGS: export
##+EXPORT_EXCLUDE_TAGS: noexport
##+LINK_UP:
##+LINK_HOME:


* Implementation Plan
  1. [X] Make *voting* work (without permissions, user setting, admin
     config, etc.)
  2. [X] Install a test/demo site.
  3. [ ] Add *admin config*, *user settings*, *permissions*,
     permission checking, etc.
  4. [ ] Improve the *integration with facebook* (for voting).
  5. [ ] Put it online.
  6. [ ] Improve the *email interface* (for voting).
  7. [ ] Add a *mobile interface* (or theme).
  8. [ ] Build the pages for admin dashboard, reports and stats.
  9. [ ] Add an API for external applications.
  10. [ ] Integration with google+, twitter, diaspora, etc.
  11. [ ] Android app that can be used for voting.

* Tasks

** DB

*** In the table of strings, add a reference to the previous (deprecated) string.

** UI

*** List of *string-->translations*
    + Define and implement suitable access rights.
    + Some of the advanced filtering options should be available
      only if the user has propper access rights.
    + Some editing options should be available only if the user has
      propper access rights.
    + For each suggestion, the admin (or moderators) should be able to apply
      additional actions (for example remove the suggestion).

    + For each l10n string, display in which projects it occurs
      (related locations), etc.
    + For each l10n string, display also the corresponding translations
      (best suggestions) in auxiliary (helper) languages. For example,
      besides the original l10n string (in English), the French and German
      translations may be displayed as well, if these are selected on
      the display options of the filter.

    + For each suggestion, add a Like (or +1) button. When it is clicked,
      the vote is submitted through an AJAX call. The voted (or liked,
      or +1'd) suggestion should be visibly distinguished from the rest.
    + For each suggestion, display details like: suggested by, suggested
      when, number of votes, some of the latest voters (and all the voters
      when clicked).
    + For each suggestion add a Flag (or -1) button. A suggestion is flagged
      when it is totally irrelevant to the string, or is spam, or is abusive, etc.
      In general, when a suggestion is flagged, it is something that should be
      removed. When flagging a suggestion, a reason/explanation may be given as
      well. When a suggestion is flagged, it has to be reviwed and removed
      by an admin/moderator. The admin may also take some action on the user that
      submitted the offending suggestion (or on the user that submitted the flag,
      if the suggestion is ok).

    + Voting mode can be 'single' or 'multiple', and it can be selected by admin
      (during installation). On mode 'single' at most one vote per string is allowed.
      On mode 'multiple' at most one vote for translation is allowed (user can
      approve more than one translation for the same string).
    + For the 'multiple' mode, an Unlike button should be available as well (in order
      to change the voting at any time).
    + When the votes are changed, the old (removed) votes should be stored on
      an archive table, in order to keep the history of changing votes as well.


*** TODO XML-RPC interface
    Or some other web-service (API) interface.

** Misc
   - Start with simple tests (l10n_feedback.test)
   - Improve instalation.
   - Make an initial package.
*** Add in l10n-sq.org a page for each project which can be liked, +1-d, etc.
*** Add export_tgz as a drush command.
*** Send full html pages by email.
*** Use GoogleTranslate API to make an initial suggestion for strings with no translation.
    It has become commercial. Cannot be done.
*** Improve the look of number of votes.
*** Add the possibility to leave comments/discussions under each string-lng


* Notes

** How to create TAGS for Emacs

   find . -type f | etags -
   find . -type f \( -name "*.module" -o -name "*.install" -o -name "*.inc" \) | etags -a --language=php -

   See: http://drupal.org/node/59868

** Fine-Tuning MySQL Full-Text Search

   http://dev.mysql.com/doc/refman/5.0/en/fulltext-fine-tuning.html
   http://dev.mysql.com/doc/refman/5.0/en/fulltext-search.html

   We want to index even short words and to disable stopword filtering.

   1. Edit /etc/mysql/my.cnf and set:

      [mysqld]
      ft_min_word_len = 1
      ft_stopword_file = ''

      [isamchk]
      ft_min_word_len = 1
      ft_stopword_file = ''

   2. Restart the server: service mysql restart
   3. Drop and recreate fulltext indexes.

** How to use simple REST API for exporting projects

*** List:
    wget --no-check-certificate -O list.txt https://l10n-sq.org/translations/project/list
    cat list.txt
    wget --no-check-certificate -O list.txt https://l10n-sq.org/translations/project/list/GNOME
    wget --no-check-certificate -O list.txt https://l10n-sq.org/translations/project/list/GNOME/a*
    wget --no-check-certificate -O list.txt https://l10n-sq.org/translations/project/list/*/kturtle
    wget --no-check-certificate -O list.txt https://l10n-sq.org/translations/project/list/*/kturtle/json
    wget --no-check-certificate -O list.txt https://l10n-sq.org/translations/project/list/*/-
    wget --no-check-certificate -O list.txt https://l10n-sq.org/translations/project/list/*/*turtle*/text

*** Export:
    wget --no-check-certificate -O test1.po https://l10n-sq.org/translations/project/export/KDE/kturtle/sq
    vim test1.po

*** LibreOffice:
    + List:
      wget --no-check-certificate -O list.txt \
             https://l10n-sq.org/translations/project/list/LibreOffice
      cat list.txt

    + Export:
      wget --no-check-certificate -O LibreOffice-sw-fr.tgz \
             https://l10n-sq.org/translations/project/export_tgz/LibreOffice/sw/fr
      tar tvfz LibreOffice-sw-fr.tgz
      tar xfz LibreOffice-sw-fr.tgz

    + Export all the projects:
      wget --no-check-certificate -O LibreOffice-all-fr.tgz \
             https://l10n-sq.org/translations/project/export_tgz/LibreOffice/all/fr
      tar tvfz LibreOffice-all-fr.tgz
      tar xfz LibreOffice-all-fr.tgz

*** Mozilla:
    + List:
      wget --no-check-certificate -O list.txt \
             https://l10n-sq.org/translations/project/list/Mozilla
      cat list.txt

    + Export:
      wget --no-check-certificate -O Mozilla-browser-fr.tgz \
             https://l10n-sq.org/translations/project/export_tgz/Mozilla/browser/fr
      tar tvfz Mozilla-browser-fr.tgz
      tar xfz Mozilla-browser-fr.tgz

    + Export all the projects:
      wget --no-check-certificate -O Mozilla-all-fr.tgz \
             https://l10n-sq.org/translations/project/export_tgz/Mozilla/all/fr
      tar tvfz Mozilla-all-fr.tgz
      tar xfz Mozilla-all-fr.tgz


** How to use simple REST API to get diffs

*** Get a list of diffs:
    wget -q --no-check-certificate -O list.txt https://test.l10n-sq.org/translations/project/diff/Mozilla/browser/sq ; cat list.txt
    wget -q --no-check-certificate -O list.txt https://test.l10n-sq.org/translations/project/diff/LibreOffice/sw/sq ; cat list.txt
    wget -q --no-check-certificate -O list.txt https://test.l10n-sq.org/translations/project/diff/KDE/kdelibs/sq ; cat list.txt
    wget -q --no-check-certificate -O list.txt https://test.l10n-sq.org/translations/project/diff/ubuntu/pingus/sq ; cat list.txt

*** Get a specific diff:
    wget -q --no-check-certificate -O Mozilla-browser-sq.2.diff https://test.l10n-sq.org/translations/project/diff/Mozilla/browser/sq/2
    wget -q --no-check-certificate -O Mozilla-browser-sq.2.ediff https://test.l10n-sq.org/translations/project/diff/Mozilla/browser/sq/2/ediff
    wget -q --no-check-certificate -O LibreOffice-sw-sq.2.diff https://test.l10n-sq.org/translations/project/diff/LibreOffice/sw/sq/2
    wget -q --no-check-certificate -O LibreOffice-sw-sq.2.ediff https://test.l10n-sq.org/translations/project/diff/LibreOffice/sw/sq/2/ediff
    wget -q --no-check-certificate -O KDE-kdelibs-sq.2.diff https://test.l10n-sq.org/translations/project/diff/KDE/kdelibs/sq/2
    wget -q --no-check-certificate -O KDE-kdelibs-sq.2.ediff https://test.l10n-sq.org/translations/project/diff/KDE/kdelibs/sq/2/ediff


*** Get the current diff:
    This is the diff between the current state and the last snapshot.
    It is not stored yet in the DB (it will be stored if we get
    another snapshot).

    wget -q --no-check-certificate -O Mozilla-browser-sq.current.diff https://test.l10n-sq.org/translations/project/diff/Mozilla/browser/sq/-
    wget -q --no-check-certificate -O Mozilla-browser-sq.current.ediff https://test.l10n-sq.org/translations/project/diff/Mozilla/browser/sq/-/ediff
    wget -q --no-check-certificate -O LibreOffice-sw-sq.current.diff https://test.l10n-sq.org/translations/project/diff/LibreOffice/sw/sq/-
    wget -q --no-check-certificate -O LibreOffice-sw-sq.current.ediff https://test.l10n-sq.org/translations/project/diff/LibreOffice/sw/sq/-/ediff
    wget -q --no-check-certificate -O KDE-kdelibs-sq.current.diff https://test.l10n-sq.org/translations/project/diff/KDE/kdelibs/sq/-
    wget -q --no-check-certificate -O KDE-kdelibs-sq.current.ediff https://test.l10n-sq.org/translations/project/diff/KDE/kdelibs/sq/-/ediff

** Misc

   + Field sguid:char(40) on strings, locations and translations must
     be of the same character set, otherwise mysql will not use the
     index (primary key) on queries. The same for the field tguid.

   + Crontab entry:
     0 4 * * *  wget -O - -q -t 1 --no-check-certificate https://test.l10n-sq.org/cron.php?cron_key=YVVQ7X8AmcbpDYEF_NGXISgbC-5z7_pOvxpjYEm2B_M
