#!/bin/bash -x
# executed after apply-debs

### install drush
pear channel-discover pear.drush.org
pear install pear.drush.org/drush-5.8.0

### by default use the B-Translator root directory for Drush
mkdir -p /etc/drush
cat > /etc/drush/drushrc.php << EOF
<?php
// by default use the B-Translator root directory
\$options['r'] = '/var/www/btranslator';
EOF

### install drush_make
rm -rf /usr/share/php/drush/commands/drush_make
cd /usr/share/php/drush/commands
wget http://ftp.drupal.org/files/projects/drush_make-6.x-2.3.tar.gz
tar xfz drush_make-6.x-2.3.tar.gz
cd /

### get pology (used for making embedded diffs)
rm -rf /usr/local/lib/pology
svn checkout svn://anonsvn.kde.org/home/kde/trunk/l10n-support/pology /usr/local/lib/pology
