#!/bin/bash -ex
# executed before apply-debs

source $(dirname $0)/functions

# install security updates
# better to do them here once than force every user later
install_updates

# remove old kernel images after update
cleanup_images

### install other needed packages
install nginx nginx-common nginx-full mysql-server msmtp memcached php5-memcached \
        php5-mysql php5-gd php-db php5-dev make php-pear php5-curl php-apc \
        ssl-cert gawk webmin-mysql webmin-phpini phpmyadmin \
        git mercurial subversion translate-toolkit

### install php5-fpm
cat <<EOF > /etc/apt/sources.list.d/dotdeb.list
deb http://packages.dotdeb.org stable all
deb-src http://packages.dotdeb.org stable all
EOF
wget http://www.dotdeb.org/dotdeb.gpg -O- | apt-key add -
install php5-fpm

# install uploadprogress bar (from PECL) (requested by Drupal 7)
pecl install uploadprogress
echo "extension = uploadprogress.so" > /etc/php5/conf.d/uploadprogress.ini

