#!/bin/bash -x
# executed before apply-overlay

### retrieve all the projects/modules and build the application directory
makefile="https://raw.github.com/dashohoxha/B-Translator/master/build-btranslator.make"
appdir="/var/www/btranslator"
rm -rf $appdir
drush make --prepare-install --force-complete \
           --contrib-destination=profiles/btranslator \
           $makefile $appdir

### settings for the database and the drupal site
db_name=btranslator
db_user=btranslator
db_pass=btranslator
site_name="B-Translator"
site_mail="admin@example.com"
account_name=admin
account_pass=admin
account_mail="admin@example.com"

### create the database and user
mysql_commands="
    DROP DATABASE IF EXISTS $db_name;
    CREATE DATABASE $db_name;
    GRANT ALL ON $db_name.* TO $db_user@localhost IDENTIFIED BY '$db_pass';
"
echo "$mysql_commands" | mysql -u root

### start site installation
sed -e '/memory_limit/ c memory_limit = -1' -i /etc/php5/cli/php.ini
cd $appdir
drush site-install --verbose --yes btranslator \
      --db-url="mysql://$db_user:$db_pass@localhost/$db_name" \
      --site-name="$site_name" --site-mail="$site_mail" \
      --account-name="$account_name" --account-pass="$account_pass" --account-mail="$account_mail"

### update to the latest version of core and modules
drush --yes pm-update

### set propper directory permissions
mkdir -p sites/default/files/
chown -R www-data: sites/default/files/
mkdir -p cache/
chown -R www-data: cache/
