#!/bin/bash -ex
# executed before apply-overlay

source $(dirname $0)/functions

### install php5-fpm
cat <<EOF > /etc/apt/sources.list.d/dotdeb.list
deb http://packages.dotdeb.org stable all
deb-src http://packages.dotdeb.org stable all
EOF
wget http://www.dotdeb.org/dotdeb.gpg -O- | apt-key add -
install php5-fpm

exit 1

### retrieve all the projects/modules and build the application directory
makefile="https://raw.github.com/dashohoxha/B-Translator/master/build-btranslator.make"
appdir="/usr/local/share/btranslator"
rm -rf $appdir
drush make --prepare-install \
           --contrib-destination=profiles/btranslator \
           $makefile $appdir

### settings for the database and the drupal site
db_name=btranslator
db_user=btranslator
db_pass=btranslator
site_name="B-Translator"
site_mail="admin@example.com"
account_name=admin
account_pass=admin
account_mail="admin@example.com"

### create the database and user
mysql_commands="
    DROP DATABASE IF EXISTS $db_name;
    CREATE DATABASE $db_name;
    GRANT ALL ON $db_name.* TO $db_user@localhost IDENTIFIED BY '$db_pass';
"
echo "$mysql_commands" | mysql -u root

### go to the application directory

### start site installation
sed -e '/memory_limit/ c memory_limit = -1' -i /etc/php5/cli/php.ini
cd $appdir
#set -x  # debugging
drush site-install --verbose --yes btranslator \
      --db-url="mysql://$db_user:$db_pass@localhost/$db_name" \
      --site-name="$site_name" --site-mail="$site_mail" \
      --account-name="$account_name" --account-pass="$account_pass" --account-mail="$account_mail"

### set propper directory permissions
mkdir -p sites/default/files/
chown -R www-data: sites/default/files/
mkdir -p cache/
chown -R www-data: cache/
