<?php
/**
 * Translation languages supported by the B-Translator Server.
 * Do not remove 'fr', because sometimes French translations
 * are used instead of template files (when they are missing).
 */
$arr_langs = array(
  'fr' => array(
    'code' => 'fr',
    'name' => 'French',
    'encoding' => 'latin1',
    'direction' => LANGUAGE_LTR,
    'plurals' => 2,
  ),
  'sq' => array(
    'code' => 'sq',
    'name' => 'Albanian',
    'encoding' => 'latin1',
    'direction' => LANGUAGE_LTR,
    'plurals' => 2,
  ),
);
