<?php
/**
 * @file
 * Module file for btranslator_data.
 */

require_once(dirname(__FILE__) . '/btranslator_data.menu.inc');
require_once(dirname(__FILE__) . '/includes/functions.inc');
require_once(dirname(__FILE__) . '/includes/cron.inc');

/**
 * Implements hook_help().
 */
                               /*
function btranslator_data_help($path, $args) {
  switch($path)
    {
      case 'translations/get':
        $help = t('Get translation suggestions for a given string.');
        break;

      case 'translations/vote':
        $help = t('Vote the best translation for a string, or suggest a better translation.');
        break;
    }

  return $help;
}
                               */

/**
 * Implement hook_mail().
 *
 * This hook defines a list of possible e-mail templates that this module can
 * send. Each e-mail is given a unique identifier, or 'key'.
 *
 * $message comes in with some standard properties already set: 'to' address,
 * 'from' address, and a set of default 'headers' from drupal_mail(). The goal
 * of hook_mail() is to set the message's 'subject' and 'body' properties, as
 * well as make any adjustments to the headers that are necessary.
 *
 * The $params argument is an array which can hold any additional data required
 * to build the mail subject and body; for example, user-entered form data, or
 * some context information as to where the mail request came from.
 *
 * Note that hook_mail() is not actually a hook. It is only called for a single
 * module, the module named in the first argument of drupal_mail(). So it's
 * a callback of a type, but not a hook.
 */
function btranslator_data_mail($key, &$message, $params) {
  switch ($key) {
    case 'notifications':
    default:
      $message['subject'] = $params['subject'];
      $message['body'] = $params['body'];
      break;
  }
}


/**
 * Implements hook_init().
 */
function btranslator_data_init() {

  /*
  // Set the parameters of the btranslator_data database.
  global $databases;
  $databases['btr_db']['default'] = array (
      'database' => 'l10n_tst',
      'username' => 'l10n_tst',
      'password' => 'l10n_tst',
      'host' => 'localhost',
      'port' => '',
      'driver' => 'mysql',
      'prefix' => '',
   );

  // Somehow, declaring the database here does not work.
  // Instead, this should be added to settings.php, and then
  // it will work.

  */

  // Get a connection to the btr_db. All the queries
  // of the btranslator_data module will use this connection.
  if (isset($GLOBALS['databases']['btr_db']['default'])) {
    $GLOBALS['btr_db'] = Database::getConnection('default', 'btr_db');
  }
  else {
    $GLOBALS['btr_db'] = Database::getConnection('default', 'default');
  }
}

/**
 * Implements hook_flush_caches().
 * Add cache table names to the list of cache tables
 * that will be cleared by the Clear button on the Performance page
 * or whenever drupal_flush_all_caches is invoked.
 * Returns an array of cache table names.
 */
function btranslator_data_flush_caches() {
  return array('cache_btranslator_data');
}

