<?php
/**
 * @file
 * Module file for btranslator_data.
 */

require_once(dirname(__FILE__) . '/includes/common.inc');
require_once(dirname(__FILE__) . '/btranslator_data.menu.inc');
require_once(dirname(__FILE__) . '/includes/cron.inc');

/**
 * Implements hook_help().
 */
                               /*
function btranslator_data_help($path, $args) {
  switch($path)
    {
      case 'translations/get':
        $help = t('Get translation suggestions for a given string.');
        break;

      case 'translations/vote':
        $help = t('Vote the best translation for a string, or suggest a better translation.');
        break;
    }

  return $help;
}
                               */

/**
 * Implements hook_init().
 */
function btranslator_data_init() {

  /*
  // Set the parameters of the btranslator_data database.
  global $databases;
  $databases['btr_db']['default'] = array (
      'database' => 'l10n_tst',
      'username' => 'l10n_tst',
      'password' => 'l10n_tst',
      'host' => 'localhost',
      'port' => '',
      'driver' => 'mysql',
      'prefix' => '',
   );

  // Somehow, declaring the database here does not work.
  // Instead, this should be added to settings.php, and then
  // it will work.

  */

  // Get a connection to the btr_db. All the queries
  // of the btranslator_data module will use this connection.
  if (isset($GLOBALS['databases']['btr_db']['default'])) {
    $GLOBALS['btr_db'] = Database::getConnection('default', 'btr_db');
  }
  else {
    $GLOBALS['btr_db'] = Database::getConnection('default', 'default');
  }
}

/**
 * Implements hook_flush_caches().
 * Add cache table names to the list of cache tables
 * that will be cleared by the Clear button on the Performance page
 * or whenever drupal_flush_all_caches is invoked.
 * Returns an array of cache table names.
 */
function btranslator_data_flush_caches() {
  return array('cache_btranslator_data');
}

