<?php
/**
 * @file
 * Functions called from the front-end (UI).
 */

include_once dirname(__FILE__) . '/get_strings.inc';
include_once dirname(__FILE__) . '/user.inc';
include_once dirname(__FILE__) . '/get_sguid.inc';
include_once dirname(__FILE__) . '/vocabulary_term.inc';
include_once dirname(__FILE__) . '/statistics.inc';
include_once dirname(__FILE__) . '/votes_and_translations.inc';
include_once dirname(__FILE__) . '/build_search_query.inc';
include_once dirname(__FILE__) . '/misc.inc';


