#!/bin/bash -ex
# executed after apply-overlay

echo 'core' > /etc/hostname
echo 'turnkey-core-precise' > /etc/turnkey_version

### generate locales
locale-gen en_US.UTF-8
LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 update-locale
dpkg-reconfigure localepurge