#!/bin/bash -e
# regenerate drupal7 mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/etc/dbconfig-common/drupal7.conf
sed -i "s/dbc_dbpass=\(.*\)/dbc_dbpass=\'$PASSWORD\'/" $CONF

CONF=/etc/drupal7/sites/default/dbconfig.php
sed -i "s/\$dbpass=\(.*\)/\$dbpass=\'$PASSWORD\';/" $CONF

CONF=/etc/drupal7/sites/default/settings.php
sed -i "/^\s*"\'"password"\'"/  s/=>\s*\(.*\)"\'"/=> "\'"$PASSWORD"\'"/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=drupal7 --pass="$PASSWORD"
