
This is a TKLpatch for installing B-Translator on Turnkey Linux 12.x
(for more details see: http://www.turnkeylinux.org/docs/tklpatch)


* How to install a B-Translator server using this TKL patch

  There are two ways to install a B-Translator server using this patch.

** The recommended one:

    1. Download the ISO of TurnKey Core from:
       http://www.turnkeylinux.org/core

    2. Install /tklpatch/:
       #+BEGIN_EXAMPLE
       cat <<EOF > /etc/apt/sources.list.d/tkl.list
       deb http://archive.turnkeylinux.org/ubuntu lucid main
       deb http://archive.turnkeylinux.org/ubuntu lucid universe
       EOF
       apt-get update
       apt-get install tklpatch
       #+END_EXAMPLE

    3. Get the code of B-Translator from github:
       #+BEGIN_EXAMPLE
       git clone https://github.com/dashohoxha/B-Translator.git
       #+END_EXAMPLE

    4. Apply the patch to the ISO:
       #+BEGIN_EXAMPLE
       tklpatch turnkey-core-12.0-squeeze-x86.iso B-Translator/tklpatch/
       mv turnkey-core-12.0-squeeze-x86.iso turnkey-btranslator-12.0-squeeze-x86.iso
       #+END_EXAMPLE

    5. Use the new ISO to install a B-Translator server.


** Another way:

    1. Download the ISO of TurnKey Core from:
       http://www.turnkeylinux.org/core

    2. Install it to a server.

    3. Install /tklpatch/ in the server:
       #+BEGIN_EXAMPLE
       apt-get update
       apt-get install tklpatch     
       #+END_EXAMPLE

    4. From within the installed server, get the code of B-Translator:
       #+BEGIN_EXAMPLE
       git clone https://github.com/dashohoxha/B-Translator.git
       #+END_EXAMPLE

    5. Apply the patch to the root of the installed sytem (from inside it):
       #+BEGIN_EXAMPLE
       tklpatch-apply / B-Translator/tklpatch/
       #+END_EXAMPLE


* How the patch is applied

  1. The script =conf/pre-debs= is executed.
  2. Any custom  packages on ~debs/~ are installed.
  3. The script =conf/post-debs= is executed.
  4. The script =conf/pre-overlay= is executed.
  5. The files on ~overlay/~ are copied over to the target system.
  6. The script =conf/post-overlay= is executed.

  Also, when the system is booted for the first time, the
  configuration/customization scripts that are placed on
  ~/usr/lib/inithooks~ will be executed. (See:
  http://www.turnkeylinux.org/docs/inithooks)


* How to test the patch on a chroot environment

  While working to develop or improve the patch, it is important to be
  able to test the changes. This can be done by applying the patch on
  a /chroot/ environment, as described here.

  + Download the ISO of TurnKey Core from:
    http://www.turnkeylinux.org/core

  + Extract the appliance's filesystem and cdroot from the ISO:
    #+BEGIN_EXAMPLE
    mkdir test/
    cd test/
    tklpatch-extract-iso ../turnkey-core-12.0-squeeze-x86.iso
    ln -s turnkey-core-12.0-squeeze-x86.rootfs/ rootfs
    #+END_EXAMPLE

  + Mount the patch inside the /rootfs/:
    #+BEGIN_EXAMPLE
    git clone https://github.com/dashohoxha/B-Translator.git
    mkdir rootfs/btranslator/
    mount -o bind B-Translator/tklpatch/ rootfs/btranslator
    #+END_EXAMPLE

  + Stop the web services on the main system:
    #+BEGIN_EXAMPLE
    service php5-fpm stop
    service memcached stop
    service mysql stop
    service nginx stop
    service apache2 stop
    #+END_EXAMPLE

  + Switch to the chroot environment:
    #+BEGIN_EXAMPLE
    tklpatch-chroot rootfs/
    #+END_EXAMPLE

  + Install /tklpatch/ inside the chroot environment:
    #+BEGIN_EXAMPLE
    apt-get update
    apt-get -y install tklpatch     
    #+END_EXAMPLE

  + Apply the patch inside the chroot:
    #+BEGIN_EXAMPLE
    TKLPATCH_DEBUG=y tklpatch-apply / /btranslator

    or

    /btranslator/conf/pre-debs
    tklpatch-apply-debs / /btranslator/debs/
    /btranslator/conf/post-debs
    /btranslator/conf/pre-overlay
    tklpatch-apply-overlay / /btranslator/overlay/
    /btranslator/conf/post-overlay
    #+END_EXAMPLE

  + Start the web services from inside the chroot environment:
    #+BEGIN_EXAMPLE
    mount -a
    service php5-fpm start
    service memcached start
    service mysql start
    service nginx start
    service webmin start
    service shellinabox start
    #+END_EXAMPLE

  + Test, fix the patch, apply it again, restart services, etc.

  + Test also the scripts in ~/usr/lib/inithooks~.
