#!/bin/bash -e
# Copyright (c) 2009 Alon Swartz <alon@turnkeylinux.org> - all rights reserved

fatal() {
    echo "fatal: $@" 1>&2
    exit 1
}

usage() {
cat<<EOF

Syntax: $(basename $0) rootfs-dir overlay-dir

Makes a diff between the files in overlay-dir and
the corresponding files on rootfs-dir.

Environment variables:
    TKLPATCH_DEBUG       Turn on debugging.
EOF
    exit 1
}

if [[ "$#" != "2" ]]; then
    usage
fi

[ -n "$TKLPATCH_DEBUG" ] && set -x

rootfs=$1
overlay=$2

[ -d $rootfs ] || fatal "no such directory: $rootfs"
[ -d $overlay ] || fatal "no such directory: $overlay"

tmpdir=/tmp/overlay_diff_$$
mkdir $tmpdir

# get a list of files on $overlay
find $overlay -type f | sed -e "s#^$overlay##" > $tmpdir/files.txt

# archive files from $rootfs that are on this list
tar --create --gzip \
    --directory=$rootfs \
    --files-from=$tmpdir/files.txt \
    --file=$tmpdir/files.tgz

# extract them on a tmp directory
mkdir -p $tmpdir/overlay
tar --extract --gunzip \
    --directory=$tmpdir/overlay \
    --file=$tmpdir/files.tgz

# make the diff between overlay and files from rootfs
diff -rubB $overlay $tmpdir/overlay

# clean up
rm -rf $tmpdir
