
Instructions for installing a development/production copy of
B-Translator.

* Packages
  #+BEGIN_EXAMPLE
  apt-get update
  apt-get install aptitude
  aptitude update
  aptitude upgrade
  tasksel install lamp-server
  aptitude install phpmyadmin
  aptitude install drush php5-curl php-apc php-elisp
  aptitude install git
  aptitude install gawk
  aptitude install mercurial           ### for getting Mozilla files
  aptitude install translate-toolkit   ### provides moz2po and po2moz
  #+END_EXAMPLE

* Apache2 configuration

  + Enable SSL Name-Based virtual hosting.
    - Enable mode /ssl/: ~a2enmod ssl~

    - Edit ~/etc/apache2/ports.conf~ and add the line
      ~NameVirtualHost *:443~:
      #+BEGIN_EXAMPLE
      <IfModule mod_ssl.c>
        # If you add NameVirtualHost *:443 here, you will also have to change
        # the VirtualHost statement in /etc/apache2/sites-available/default-ssl
        # to <VirtualHost *:443>
        # Server Name Indication for SSL named virtual hosts is currently not
        # supported by MSIE on Windows XP.
        NameVirtualHost *:443
	  Listen 443
      </IfModule>
      #+END_EXAMPLE

    - Edit ~/etc/apache2/sites-available/default-ssl~ and change
      the VirtualHost statement (at the top) to ~<VirtualHost
      *:443>~, like this:
      #+BEGIN_EXAMPLE
      <IfModule mod_ssl.c>
      <VirtualHost *:443>
      #+END_EXAMPLE

    - Then restart apache: ~service apache2 restart~

  + Enable apache modules /headers/ and /rewrite/:
    #+BEGIN_EXAMPLE
    a2enmod headers
    a2enmod rewrite
    service apache2 restart
    #+END_EXAMPLE

  + Create configuration files ~/etc/apache2/sites-available/l10n~,
    and ~/etc/apache2/sites-available/l10n-ssl~ by copying ~default~
    and ~default-ssl~ and modifying them like this:
    #+BEGIN_EXAMPLE
    <VirtualHost *:80>
        ServerName l10n-dev.org.al
	ServerAdmin dashohoxha@gmail.com

	DocumentRoot /var/www/l10n-dev.org.al
	<Directory />
	    Options FollowSymLinks
	    AllowOverride None
        </Directory>
        <Directory /var/www/l10n-dev.org.al/>
            Options Indexes FollowSymLinks MultiViews
	    #AllowOverride None
	    AllowOverride All   ### this is needed for clean URLs
            Order allow,deny
	    allow from all
        </Directory>
    #+END_EXAMPLE

    #+BEGIN_EXAMPLE
    <IfModule mod_ssl.c>
    <VirtualHost *:443>
        ServerName l10n-dev.org.al
	ServerAdmin dashohoxha@gmail.com

	DocumentRoot /var/www/l10n-dev.org.al
        <Directory />
            Options FollowSymLinks
            AllowOverride None
        </Directory>
	<Directory /var/www/drupal/>
	    Options Indexes FollowSymLinks MultiViews
	    #AllowOverride None
	    AllowOverride All   ### this is needed for clean URLs
	    Order allow,deny
	    allow from all
	</Directory>
    #+END_EXAMPLE

  + Add this line to ~/etc/fstab~
    #+BEGIN_EXAMPLE
    127.0.0.1    l10n-dev.org.al
    #+END_EXAMPLE

  + Enable the sites ~l10n~ and ~l10n-ssl~:
    #+BEGIN_EXAMPLE
    a2ensite l10n
    a2ensite l10n-ssl
    #+END_EXAMPLE

    Then rename the links on ~/etc/apache2/sites-enables~ like this:
    #+BEGIN_EXAMPLE
    000-l10n  000-l10n-ssl  001-default  001-default-ssl
    #+END_EXAMPLE

  + At ~/etc/php5/apache2/php.ini~ set ~display_errors = On~ and restart apache.

  + Finally restart apache: =service apache2 restart=.


* Drupal configuration

  + On /Site information/ page
    (=/admin/config/system/site-information=) set email address to your
    email address (for example ~dashohoxha+btranslator@gmail.com~).  Modify
    also the site name and slogan.

  + Disable temporarily the facebook app, at
    =/admin/structure/fb/app=

  + Install module SMTP Authentication support and enable and
    configure it (at =/admin/config/system/smtp=):
    - Set SMTP server to: ~smtp.googlemail.com~
    - SMTP Port: ~465~
    - Use encrypted protocol: ~Use SSL~
    - SMTP authentication username: ~dashohoxha@gmail.com~ (set
      the password as well)
    - Email from address: ~dashohoxha+btranslator@gmail.com~
    - Email from name: ~btranslator~
    - Allow to send email formatted as html: ~checked~
    - Sends also a test email to ~dashohoxha+test@gmail.com~

  + On the configuration of Boost (~/admin/config/system/boost~)
    disable cache for the page /translations/.

  + Create directory ~cache/~ (which is used by /Boost/) and make it
    writable by /apache/:
    #+BEGIN_EXAMPLE
    mkdir -p cache/
    chown www-data: -R cache/
    #+END_EXAMPLE

  + Enable displaying file upload progress through APC:
    - Install /php-apc/: ~aptitude install php-apc~
    - Edit ~/etc/php5/apache2/php.ini~ and add this line: ~apc.rfc1867 = 1~
    - Restart /apache2/: ~service apache2 restart~

  + Configure /cron/:
    - Enable rerouting of emails, at
      =/admin/config/development/reroute_email= and set the reroute
      email to ~dashohoxha@gmail.com~
    - Disable the internal cron at =/admin/config/system/cron=
    - Run =crontab -e= and add these lines:
      #+BEGIN_EXAMPLE
      ### https://l10n-dev.org.al
      0 2 * * *  wget -O - -q -t 1 --no-check-certificate https://l10n-dev.org.al/cron.php?cron_key=YVXQ7X8AmcbpDYEF_NGXISgbC-5z7_pOvxpjYEm2B_M
      #+END_EXAMPLE
    - Test it by running this command from command line:
      #+BEGIN_EXAMPLE
      wget -O - -q -t 1 --no-check-certificate https://l10n-dev.org.al/cron.php?cron_key=YVXQ7X8AmcbpDYEF_NGXISgbC-5z7_pOvxpjYEm2B_M
      #+END_EXAMPLE
      For the correct cron URL to be used, check =/admin/reports/status=

