
This file is used to keep the project organized. It is based on the
org-mode of Emacs (http://orgmode.org/), which is a good tool for
keeping notes, project planning, tasks management, etc.

* Initial Plan							    :ARCHIVE:

** DONE Design DB schema
   Design a propper DB schema for l10n_suggestions. In general, it is
   going to be reacher than the open-tran.eu schema, since it is going
   to keep data about votes/evaluations/promotions of different
   suggestions.

** DONE Get open-tran.eu data
   Download it from: http://open-tran.eu/dev.html

** TODO Import data
   Write a script for importing the open-tran.eu data into the
   l10n_suggestions DB (MySQL). It should:
   1. [X] dump the data from the SQLite db
   2. [X] import them into MySQL
   3. [X] rearrange them to fit the new schema requirements
   4. [ ] take care of both an initial import and an update (in the
      case of update it should be carefull not to overwrite any
      existing data)

* Functional requirements
  Describe the desired functionality of the module. Then define the
  requirements in terms of forms and other UI elements, permissions,
  etc.

** Desired Functionality

*** Open access
    Everybody will be able to use the system for the purpose of getting
    translation suggestions for a certain string, even unauthenticated
    (anonymous/guest) users (just like open-tran.eu).
    Furthermore, it should be possible to use an API (web services), so
    that these suggestions can be retrieved and used even by external
    applications.

*** Authenticated voting
    Submitting votes or new suggestions will be allowed only for the
    subscribed users (which have agreed to help and contribute). No
    contributions from anonymous/guests will be accepted.

*** Tracking votes
    Votes and suggestions will not be anonymous. For each vote or
    suggestion, the user who submitted it will be recorded and
    saved. This will allow the user to see all the strings that he has
    already voted for, and also to change any of the votes, if he later
    changed his mind. At the same time it will prevent multiple votes
    by the same user for the same translation.

*** Highly customizable
    The system will have a flexible configuration and customization
    page. This means that the user should be able to customize how much
    he would like to help and contribute. For example:
     - how many translation votes per day (an upper limit)
     - which communication means he preferes (email, facebook, google+,
       twitter, website, android app, iPhone app, etc.)
     - which projects or packages he would like to focus on (for
       example, if the user selects the package KDE, only strings that
       belong to a project on this package will be sent to him for
       review and feedback)
     - which languages he would like to use as primary and secondary
       source languages (for example a user that is not confident in
       English, may choose to use French as a primary language and
       Italian+Spanish as secondary/helper languages)
     - sequential or random selection of strings (random is the
       default, but if the user is interested in just one or a few
       projects, he may prefer to review the strings sequentially)

*** Evaluation Algorithms
    The contribution and performance of the users should be measured
    and evaluated using certain algorithms and/or heuristics. The users
    will be awarded points based on their performance. Probably some
    rewarding mechanizms can be integrated later for the top
    contributers.

*** Detailed and comprehensive reporting and statistics
    Different kinds of reports and statistics related to users,
    projects, activity etc. should be supported and provided.
    (What are exactly these reports? To be elaborated.)

*** Integration with other modules
    It should be possible to integrate with other l10n modules, like
    l10n_server, etc. When a new project is added on l10n_server, the
    strings that need to be translated can get some suggestions
    automatically from l10n_suggestions. Or they can be submitted to
    l10n_suggestions so that people can supply translation and
    suggestions for them, to vote on these suggestions, etc.

    The manager of the project on l10n_server may also adjust some
    configuration parameters related to the suggestions. For example a
    suggestion can be accepted as a correct translation only if it got
    75% of all the votes about all the suggestions, otherwise it
    should be considered as fuzzy translation and needs to be reviewed
    by the package manager.


** Required forms

*** Query interface
    On this form anybody (registered user or anonymous) can
    supply a string in English, and the system will return the
    translation suggestions related to it and the corresponding votes
    that each suggestion has.

    If the English string does not have an exact match on the DB, a
    list of similar strings will be returned and the user will choose
    toc check one of them.

    This functionality of querying suggestions will be offered also by
    a web service (XMLRPC) so that it can be used by any external
    programs.

*** Suggestion interface
    This is the form where the (authenticated) user is presented with
    an English string and several translation suggestions for it, and
    he votes on one of them as the best, or provides another
    suggestion which he thinks is better.

    The string to be translated is selected randomly, unless the user
    has selected 'sequential' on his settings. The selection of the
    string is also done so that it complies with the restrictions
    imposed by the user on his settings (for example only from a
    certain package).

    The selection of the string should be also influenced by certain
    algoriths and heuristics, which should try to give more exposure
    to the strings that need more votes. For example if a string
    already got 10 votes and another one got just 2 votes, the second
    one should be more likely to be selected.

    This interface should be able to integrate somehow with facebook,
    email, google+, etc.

*** User configuration interface
    Here the user customizes his setings, as described in the section
    'Desired Functionality' above.

*** Admin interfaces
    The admin should be able to customize the overall behaviour of the
    module, to check activity, to get reports and statistics, to
    maintain the data (backup, restore, update) etc.

*** Other modules interfaces
    In case of integration with other modules (for example with
    l10n_server), l10n_suggestions should alter their forms and
    interfaces to add the neccessary options and settings.


* Design

** DB Schema

   The DB tables and their fields:

   + Locations :: Locations (lines) where a phrase (string) is found.
     - lid : serial :: Internal numeric identifier of a line.
     - pid : int :: Reference to the id of the phrase contained in
                    this line.
     - projectid : int :: Reference to the id of the project that
          contains this line.
     - packageid : int :: Reference to the id of the package that
          contains the project.
     - projectname : varchar(100) :: The name of the project
          containing this line.
     - flags : int :: Copied from open-trans.eu

   + Phrases :: Translatable strings and phrases that are extracted
                from projects.
     - pid : serial :: Internal numeric identifier for a phrase.
     - phrase : text :: The (English) phrase to be translated.
     - hash : binary(20) :: Will be used for a more efficient and
          reliable text comparison, searching, indexing, etc. hash =
          UNHEX(SHA1(TRIM(phrase)))
     - uid_entered : int :: ID of the user that inserted this string
          on the DB.
     - time_entered : datetime :: The time that this string was
          entered on the DB.
     - pcount : int/tiny :: How often this phrase is encountered in
          all the projects. Can be useful for any heuristics that try
          to find out which phrases need to be translated first.

   + Translations :: Translations/suggestions of the phrases
                     (strings). For each phrase/string there can be
                     translations for different languages, and more
                     than one translation for each language.
     - tid : serial :: Internal numeric identifier for a translation.
     - pid : int :: Reference to the id of the phrase that is
                    translated.
     - lng : varchar(5) :: Language code (en, fr, sq_AL, etc.)
     - translation : varchar(1000) :: The (suggested) translation of
          the phrase.
     - hash : binary(20) :: Will be used for a more efficient and
          reliable text comparison, searching, indexing, etc. hash =
          UNHEX(SHA1(TRIM(translation)))
     - vcount : int/tiny :: Count of votes received so far. This can be
          counted on the table Votes, but for convenience is stored
          here as well.
     - uid_entered : int :: id of the user that initially proposed this
                        translation
     - time_entered : datetime :: Time that the translation was
          entered into the database.

   + Votes :: Votes for each translation/suggestion.
     - vid : serial :: Internal numeric identifier for a vote.
     - tid : int :: Reference to the id of the translation which is
                    voted.
     - uid : int :: Reference to the id of the user that submitted the
                    vote.
     - vtime : datetime :: Timestamp of the voting time.

   + Users :: Users that contribute translations/suggestions/votes.
     - uid : int :: The numeric identifier of the user.
     - points : int :: Number of points rewarded for his activity.
     - config : varchar(250) :: Serialized configuration variables.

*** Issues
    - Store multiple plurals in different records or in one record?
    -

** UI

*** translations/get/<lng>/<hash>

    An interface for suggesting translations to a phrase.  Gets as
    input
    - the language code to which will be translated
    - the hash of the phrase to be translated

    Returns a list of translation suggestions of the given phrase.
    This interface should be accessible by anybody.
    There should be also a corresponding XML-RPC interface, so that it
    can be accessed from external programs.

*** translations/search?lng=..&limit=..&mode=..&words=..

    Displays a list of strings and the corresponding suggestions, which
    match some filter conditions. Filter conditions can be modified on
    the interface. Search can be done by the content of the strings and
    suggestions, and can be limited in scope by the project, by the author
    of suggestions, by the submition date, etc.

    From the displayed list, it is also possible to view details (for
    string or suggestion), to submit votes, etc.

*** translations/vote

    This interface will select a random phrase and will present it and
    its available translations to the user. The user will vote one of
    them as the best translation, or will provide a new translation
    that he thinks is better.

    The original phrase is usually presented in English, but
    additional languages can be presented as well, if the user is not
    confident with English. (He can select these options on the user
    settings page as well.)

*** translations/user_settings
    The user can set:
    - the prefered source language(s)
    - how many votes a day is willing to give
    - etc.

*** translations/admin
    + translations/admin/config
    + translations/admin/dashboard
    + translations/admin/reports
    + translations/admin/stats

* Implementation Plan
  1. Make *voting* work (without permissions, user setting, admin
     config, etc.)
  2. Release an initial drupal package and prepare a test/demo site.
  3. Add *admin config*, *user settings*, *permissions*, permission
     checking, etc.
  4. Make a basic *integration with facebook* (for voting).
  5. Put it online.
  6. Add a basic *email interface* (for voting).
  7. Add a *mobile interface* (or theme).
  8. Build the pages for admin dashboard, reports and stats.
  9. Integrate with projects and packages from l10n_server
  10. Add an API for external applications.
  11. Integration with google+, twitter, diaspora, etc.
  12. Android app that can be used for voting.

* Tasks

** DB

*** TODO Write scripts for updating data from open-tran.eu
    Take care to preserve the data that already exist in the DB.

*** Misc
    + Check the plurals (how they are handled?).
    + There are cases of strings where exaclty the same translation
      is stored several times. Checkout why it happens, and try to
      fix it.
    + The function that generates the hash of a string (phrase)
      probably should be changed and improved.

** UI

*** List of *string-->translations*
    + Define and implement suitable access rights.
    + Some of the advanced filtering options should be available
      only if the user has propper access rights.
    + Some editing options should be available only if the user has
      propper access rights.
    + For each suggestion, the admin (or moderators) should be able to apply
      additional actions (for example remove the suggestion).

    + For each l10n string, display details like: submitted by, submitted when,
      in which projects it occurs (related locations), etc.
    + For each l10n string, display also the corresponding translations
      (best suggestions) in auxiliary (helper) languages. For example,
      besides the original l10n string (in English), the French and German
      translations may be displayed as well, if these are selected on
      the display options of the filter.

    + For each suggestion, add a Like (or +1) button. When it is clicked,
      the vote is submitted through an AJAX call. The voted (or liked,
      or +1'd) suggestion should be visibly distinguished from the rest.
    + For each suggestion, display details like: suggested by, suggested
      when, number of votes, some of the latest voters (and all the voters
      when clicked).
    + For each suggestion add a Flag (or -1) button. A suggestion is flagged
      when it is totally irrelevant to the string, or is spam, or is abusive, etc.
      In general, when a suggestion is flagged, it is something that should be
      removed. When flagging a suggestion, a reason/explanation may be given as
      well. When a suggestion is flagged, it has to be reviwed and removed
      by an admin/moderator. The admin may also take some action on the user that
      submitted the offending suggestion (or on the user that submitted the flag,
      if the suggestion is ok).

*** XML-RPC interface
    Or some other web-service (API) interface.

*** Interface *translation/vote*
    This is almost the same as the search interface. However, instead of
    using a filter to select strings, they are selected randomly, based
    on user preferencies, and also on the priorities of translation.

** Misc
   - rename phrases to strings, pid to sid, etc.
     (to be consistent with the terminology used in l10n_server)
   - Start with simple tests (l10n_suggestions.test)
   - Improve instalation.
   - Make an initial package.

* Notes

** How to create TAGS for Emacs

   find . -type f | etags -
   find . -type f \( -name "*.module" -o -name "*.install" -o -name "*.inc" \) | etags -a --language=php -

   See: http://drupal.org/node/59868

** Fine-Tuning MySQL Full-Text Search

   http://dev.mysql.com/doc/refman/5.0/en/fulltext-fine-tuning.html
   http://dev.mysql.com/doc/refman/5.0/en/fulltext-search.html

   We want to index even short words and to disable stopword filtering.

   1. Edit /etc/mysql/my.cnf and set:

      [mysqld]
      ft_min_word_len = 1
      ft_stopword_file = ''

      [isamchk]
      ft_min_word_len = 1
      ft_stopword_file = ''

   2. Restart the server: service mysql restart
   3. Drop and recreate fulltext indexes.

