<?php
/**
 * @file
 * Functions called from the front-end (UI).
 */

include_once dirname(__FILE__) . '/get_strings.inc';
include_once dirname(__FILE__) . '/hook_user.inc';
include_once dirname(__FILE__) . '/get_sguid.inc';
include_once dirname(__FILE__) . '/vocabulary_term.inc';
include_once dirname(__FILE__) . '/statistics.inc';
include_once dirname(__FILE__) . '/votes_and_translations.inc';
include_once dirname(__FILE__) . '/import_translations.inc';
include_once dirname(__FILE__) . '/search.inc';
include_once dirname(__FILE__) . '/misc.inc';
include_once dirname(__FILE__) . '/languages.inc';
include_once dirname(__FILE__) . '/projects.inc';
